### ISSUE TITLE
希望串列表能够显示标题和名称

### ISSUE THREAD

**Issue by Mouwoo** [fishballzzz/DawnIslandK#147]
![Screenshot_20200607_141107](https://user-images.githubusercontent.com/63538532/83961763-da713800-a8c8-11ea-91d2-722d383e2a49.jpg)
![Screenshot_20200607_141050](https://user-images.githubusercontent.com/63538532/83961765-e2c97300-a8c8-11ea-9fbc-526105c49d11.jpg)

**Comment by fishballzzz** [comment]
同时添加串id
