### ISSUE TITLE
防剧透代码无法隐藏串号

### ISSUE THREAD

**Issue by Mouwoo** [fishballzzz/DawnIslandK#149]
![Screenshot_20200609_123046_com laotoua dawnislandk](https://user-images.githubusercontent.com/63538532/84106306-5ac0a600-aa4d-11ea-8683-17a2c066b9e0.jpg)

**Comment by fishballzzz** [comment]
这是参照网页版和其他客户端的做法。应该不是bug，如果把字隐藏了，用户无法知道这是引用，点下去不会显示内容而直接触发显示引用。因为显示隐藏信息和打开引用有冲突，无法做到两个并存。要么隐藏信息改为单次触发，显示以后不能再隐藏，这样第二次点击将会触发引用。要么保持现在的效果
