### ISSUE TITLE
从热榜界面进入已被删除的串显示异常

### ISSUE THREAD

**Issue by Mouwoo** [fishballzzz/DawnIslandK#154]
APP启动后从热榜首次进入一个已被删除的串会一直显示加载中而不提示“该串已被删除”
![IMG_20200610_122736](https://user-images.githubusercontent.com/63538532/84227032-f61d4e00-ab15-11ea-830f-5e30a307d48c.jpg)
![Uploading Screenshot_20200609_233255_com.laotoua.dawnislandk.jpg…]()
返回后再次进入显示正常
![Screenshot_20200609_233258_com laotoua dawnislandk](https://user-images.githubusercontent.com/63538532/84227103-1ea54800-ab16-11ea-9edf-a8bc8ada404e.jpg)

**Comment by Mouwoo** [comment]
![Screenshot_20200609_233255_com laotoua dawnislandk](https://user-images.githubusercontent.com/63538532/84227264-7e035800-ab16-11ea-9a00-701202e0c713.jpg)
第二张图

**Comment by fishballzzz** [comment]
今天刚刚发现已经修了，请等待下一个版本
