### ISSUE TITLE
斜体字显示不完全

### ISSUE THREAD

**Issue by Mouwoo** [fishballzzz/DawnIslandK#180]
![1593532036986](https://user-images.githubusercontent.com/63538532/86147726-50656980-bb2c-11ea-9abc-e9466d28057c.jpeg)
![1593532029734](https://user-images.githubusercontent.com/63538532/86147830-71c65580-bb2c-11ea-8ff9-505296882393.jpeg)

**Comment by fishballzzz** [comment]
https://stackoverflow.com/questions/44074858/android-textview-text-get-cut-off-on-the-sides-with-custom-font
