### ISSUE TITLE
快速双击跳页按钮后关闭跳页弹窗会导致界面冻结无法进行任何交互

### ISSUE THREAD

**Issue by Mouwoo** [fishballzzz/DawnIslandK#204]
还有概率在双击后直接闪退

**Comment by fishballzzz** [comment]
这个不太确定修好没，大概不会再冻结了。。另外每个按钮都是按一下就做出反应，在按一次就可能是别的效果。如果我每个按钮都支持双击的话这个工程量就很大了。。你先测试一下新版版看看和你之前的情况一不一样
