### ISSUE TITLE
notice

### ISSUE THREAD

**Issue by yudanhezhongweijie** [fishballzzz/DawnIslandK#21]
![image](https://user-images.githubusercontent.com/43075130/79281695-49aa4d00-7e81-11ea-8812-dcf0a141ed51.png)

**Comment by fishballzzz** [comment]
2. APP启动时，检查 https://cover.acfunwiki.org/luwei.json
并覆盖当前缓存中的值
其中部分板块在发串界面有灰色的字提示版规 由rule字段判断，无rule字段则提示“请遵守总版规”
3. APP发串界面需要有较为显著的查看版规的按钮，具体呈现方式可自定，初次使用要有勾选“我已阅读理解并同意遵守全部版规和免责声明”的地方
