### ISSUE TITLE
部分设置无法保存

### ISSUE THREAD

**Issue by dd-fantasy** [fishballzzz/DawnIslandK#234]
改变设置后按两次返回退出app后部分设置不保存；但是改变设置后杀后台可以保存。
目前发现不能保存的设置有：
1. “本软件作者blahblah”的对话框，点击“我知道了”并点击关闭，下次打开还会有
2. 自定义卡片布局中改变参数之后，下次打开又变回默认了
Android Q（一加）和Pie（x86虚拟机）上都有出现。

**Comment by fishballzzz** [comment]
关于设置方面其实他是保存了的，只是我每次打开app只读取一次，所以修改了以后还是显示之前的值，必须重启app。这个问题我已经部分修复了，只不过还没发布。另外有些值影响了某些整个软件层面上的特性，所以肯定会有一些设置需要杀后台重启才能体现。不过新手使用那个确实是得杀后台，我修修
