### ISSUE TITLE
覆盖安装最新版本后已导入饼干丢失

### ISSUE THREAD

**Issue by chenyl0426** [fishballzzz/DawnIslandK#243]
复现操作：通过GitHub Release升级版本
![Screenshot_2020-08-18-22-16-58-223_com laotoua dawnislandk_Mosaic_22_17_5](https://user-images.githubusercontent.com/61819463/90524486-b40d2a00-e1a0-11ea-9fee-3eb3050996b0.jpg)

**Comment by fishballzzz** [comment]
感谢发布问题。但是这个问题好像和机型有关系，我自己两台手机都没有问题，虚拟机有一台有问题但是也没找到bug。。如果更新后发现饼干没了请重新导入饼干。后面如果找到了复现办法会再修
