### ISSUE TITLE
Base CDN 切换 按钮

### ISSUE THREAD

**Issue by Flyfish233** [fishballzzz/DawnIslandK#252]
在 #251 更新后，由于基于中国移动的网络将 adnmb3 CDN 进行屏蔽，不经 Proxy 刷不出任何内容，请求 Timeout，而 adnmb2 完全正常访问。

能否在设置中增加按钮以切换 CDN?

**Comment by fishballzzz** [comment]
@Flyfish233 已经做了一个测试版在内测群，目前还不确定稳不稳定所以还没有发布，请加群783544683下载

**Comment by Flyfish233** [comment]
> @Flyfish233 已经做了一个测试版在内测群，目前还不确定稳不稳定所以还没有发布，请加群783544683下载

未能完全替代问题：浏览功能正常走自定义 CDN。发串和回复功能仍旧采用 adnmb3 而无法连接 (SSL Handshake Timeout)

**Comment by fishballzzz** [comment]
> 
> 
> > @Flyfish233 已经做了一个测试版在内测群，目前还不确定稳不稳定所以还没有发布，请加群783544683下载
> 
> 未能完全替代问题：浏览功能正常走自定义 CDN。发串和回复功能仍旧采用 adnmb3 而无法连接 (SSL Handshake Timeout)

已修改，同时添加引用请求设置，稍后即可在群里下载

**Comment by Flyfish233** [comment]
串外引用在设置 `https://nmb.fastmirror.org` 后出现 HTTP 403

**Comment by fishballzzz** [comment]
> 串外引用在设置 `https://nmb.fastmirror.org` 后出现 HTTP 403

引用设置只能为adnmb2,3 后面我修改一下提示

**Comment by fishballzzz** [comment]
1.3.0已修复
