### ISSUE TITLE
偶现 ANR Input dispatching timed out

### ISSUE THREAD

**Issue by Flyfish233** [fishballzzz/DawnIslandK#253]
Lotcat 串号：`29890595`，在下滑时页面突然冻住无响应，之后程序自动退出。

在其他串中也有偶现，遇到多次。一般是在阅读较多回复的串 (>50) 下出现。

Logcat: [https://paste.ubuntu.com/p/35VrCRkyvP/](https://paste.ubuntu.com/p/35VrCRkyvP/)

**Comment by Flyfish233** [comment]
ANR 日志见 [https://paste.ubuntu.com/p/ksZ6qPTVmY/](https://paste.ubuntu.com/p/ksZ6qPTVmY)

**Comment by fishballzzz** [comment]
感谢分享！
我看了日志发现具体的错误是因为内存不足，但是是什么原因倒置内存不足我就不太懂了。。因为这个发生的原因太多：可能来源于一次性读取太多图片，也可能某个地方泄露内存。。这个得好好研究，如果你发现什么规律也请和我分享，说不定能更快修复
