### ISSUE TITLE
时间线无法加载

### ISSUE THREAD

**Issue by Waldenmuxi** [fishballzzz/DawnIslandK#258]
芦苇岛APP出现无法加载、发串等现象可尝试清空应用数据或卸载重装，如问题仍持续，请运行芦苇岛APP设置中的诊断程序并将诊断结果发送至 admin＠adnmb.com
今天无法加载时间线，单独打开某个板块可以加载出内容，绿岛清除数据后恢复，黎明岛清除数据无法恢复

**Comment by fishballzzz** [comment]
刚刚了解到a岛后台更新了，需要等服务器那边做一些修改，请耐心等待
