### ISSUE TITLE
希望加入记录左滑板块的功能

### ISSUE THREAD

**Issue by baker0808** [fishballzzz/DawnIslandK#264]
希望加入记录左滑板块的功能，
不然每次都要点一下常用板块，有点麻烦。

**Comment by fishballzzz** [comment]
这个功能可能不太好加，因为板块其实本来挺多的，但是我考虑加个选项可以让常用板块、串默认展开

**Comment by fishballzzz** [comment]
将会在1.6.06添加自定义展开板块设置
