### ISSUE TITLE
暗色主题需要一个a屏的黑

### ISSUE THREAD

**Issue by wryyyy4444** [fishballzzz/DawnIslandK#266]

**Comment by fishballzzz** [comment]
你好，感谢你的意见。请问可以具体描述你的问题吗？
暗色主题当前所有的颜色基本都是根据安卓系统自带的颜色来显示的，所以理论上并没有对不同的屏幕做不同的处理。我自己的手机是1+ 7t pro，平常用的黑色主题感觉没问题？

**Comment by wryyyy4444** [comment]
一加8T类原生，显示的是深灰色，和系统设置的黑色不是同一种![Screenshot_20220726-142449_黎明岛K.png](https://user-images.githubusercontent.com/34270450/180938044-35c476bc-997a-4dbc-bfdf-a96b7e3c0e20.png)![Screenshot_20220726-142454_设置.png](https://user-images.githubusercontent.com/34270450/180938295-bf6433d2-5f88-4fa1-b3d3-91544dce4c20.png)

**Comment by fishballzzz** [comment]
目前的颜色是根据material design来的。和系统里的黑不一样是因为你看到的灰色背景其实是黑色背景上面的图层。（印象中没有那个图层的话,好像东西显示就会透过去。。。

如果你想要了解或者改进现在暗色主题，可以到这里看看 https://material.io/design/color/dark-theme.html

感谢~
________________________________

**Comment by txyyh** [comment]
我补充几句吧

A 屏黑实际上是不遵守 Material Design 的
至于为啥系统还是用了 A 屏黑，这个估计就是 ROM Developer 考量后认为还是实用更重要（动态取色器里一样还是不会给出 A 屏黑）

**Comment by fishballzzz** [comment]
我去查了一下a屏黑具体实现原理，a屏黑和OLED黑是完全依靠屏幕本身不填充任何颜色而实现黑色，约等于透明，这种实现方式需要对手机屏幕本身支持。作为一个需要支持不同机型的软件，这是很难实现的。我看了几个我常用的app，每一个用的都不是这种纯黑而是一个类似暗灰色的图层。总的来说这个功能需要大量调试，我个人目前没办法支持。
