### ISSUE TITLE
跳页后再次点击跳页按钮会闪退

### ISSUE THREAD

**Issue by Mouwoo** [fishballzzz/DawnIslandK#61]
跳页完成后不进行任何操作再次点击跳页按钮会造成闪退。

**Comment by fishballzzz** [comment]
无法复现。
猜测原因是页面还在刷新的时候还没获取到adapter的数据，具体原因需要更多的测试

**Comment by fishballzzz** [comment]
在尾部显示时（没有更多数据），尾部会当成一个item读取，会出现indexoutofbounds的bug
