### ISSUE TITLE
部分系统图片存储位置不对

### ISSUE THREAD

**Issue by Mouwoo** [fishballzzz/DawnIslandK#87]
![1f6ce672a3d49285](https://user-images.githubusercontent.com/63538532/81243135-91b42e00-9041-11ea-8a22-da204d49cdd3.jpg)
机型：小米6
系统：MIUI12 20.5.6

**Comment by Flyfish233** [comment]
详细信息
图片被保存在 /data/media/0/Pictures 而非 Pictures/Dawn
小米 4
MIUI 10
